### PR TITLE
fix: use projectId from CloudStorageConfig

### LINKED ISSUE #352: Error when we try to check if a file is a directory on google buckets
We are moving to google buckets for storage as part of our cloud migration, CloudStorageFileSystem is a neat solution for this, a drop in for us.

The problem that we are facing is when we try to check if a file is a directory using: 

```
Path path = filesystem.get("testfileNotfolder");
if (Files.isDirectory(path)) {
.....
} else {
.....
}
```

It complains with an error about a missing permission:
```json
{
"code" : 403,
"errors" : [ {
"domain" : "global",
"message" : "xxxxxxxxxxxxxxxxxxxxxx does not have serviceusage.services.use access to xxxxxxxxxxxxxxxxxxx",
"reason" : "forbidden"
} ],
"message" : "xxxxxxxxxxxxxxxxxxxxxx does not have serviceusage.services.use access to project xxxxxxxxxxxxxxxxxxx."
}
```

This has been filed before as **https://github.com/googleapis/java-storage-nio/issues/61** but it never went anywhere, the current way of us having this working is granting it an editor/owner role on the project, which is too much access for a storage API credentials.

Please check the previous filed ticket, it estates that if we don't pass the project, it will work fine, which is what we want and that won't require permission: **serviceusage.services.use** and that works fine if we try to execute the code in debugging, the change isn't much.

Can you please provide a solution for this issue as this is still happening, we need either to have a way to configure not passing the project, because clearly the API works without passing it, or a way to grant that permission only to the credential of the API as it doesn't appear to be a way to do so.

This library is really convenient and having this role assigned to the storage credential will simply not work/allowed to use it in production and we will be forced to use another library.

### PR DESCRIPTION
**Pull request by frankyn**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)

Fixes #352 ☕️

### CODE REVIEW

File: google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageIsDirectoryTest.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+import com.google.cloud.testing.junit4.MultipleAttemptsRule;
+import com.google.common.collect.Lists;
+import java.nio.file.Files;
+import org.junit.Before;
+import org.junit.Rule;
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.junit.runners.JUnit4;
+
+/** Unit tests for {@link CloudStorageFileSystemProvider} late initialization. */
```
Comment (BenWhitehead) [inline google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageIsDirectoryTest.java:38]: nit: I don't think this comment is true

File: google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java [hunk 2]
```diff
@@ -103,15 +103,24 @@ boolean seemsLikeADirectoryAndUsePseudoDirectories(Storage storage) {
...
-    Page<Blob> list =
-        storage.list(
-            this.bucket(),
-            Storage.BlobListOption.prefix(prefix),
-            // we only look at the first result, so no need for a bigger page.
-            Storage.BlobListOption.pageSize(1),
-            fileSystem.provider().getProject() == null
-                ? null
-                : Storage.BlobListOption.userProject(fileSystem.provider().getProject()));
+    String userProject = fileSystem.config().userProject();
```
Comment (BenWhitehead) [inline google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java:106]: Am I understanding correctly, the bug was reading `projectId` from the `ServiceOptions` instead of from the `CloudStorageConfig`? If so, can we update the commit comment to explain this fact?

**Review by BenWhitehead — APPROVED** [review]

File: google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java (hunk 2 above)
Comment (frankyn) [reply google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java:106]: Good call, that's much clearer.

File: google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageIsDirectoryTest.java (hunk 1 above)
Comment (frankyn) [reply google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageIsDirectoryTest.java:38]: lol.... copy paste disaster over here!
