### PR TITLE
fix: FakeStorageRpc#list to filtering the files by bucket and prefix

### LINKED ISSUE #207: FakeStorageRpc: Consider filtering by bucket *and* prefix.
#### Environment details

1. FakeStorageRpc
2. OS type and version: Win 10
3. Java version: java 8
4. google-cloud-nio version(s): 0.121.2

#### Steps to reproduce

1. Add object with name "test-object" to bucket "first-bucket",
2. Add object with name "test-object" to bucket "second-bucket".
3. List objects in "first-bucket" with "test-" prefix.
4. Both "test-object" files from "first-bucket" and "second-bucket" are returned.

#### Any additional information below

The `list` method in the `FakeStorageRpc` does not take into account the `bucket` metadata:

```java
    for (StorageObject so : metadata.values()) {
      if (!so.getName().startsWith(prefix)) {                       // <---------- here's the problem
        continue;
      }
      if (processedAsFolder(so, delimiter, prefix, folders)) {
        continue;
      }
      so.setSize(size(so));
      values.add(so);
    }
```

Technically, just adding an extra check to compare the `so.getBucket()` with `bucket` should be enough to resolve the issue.

### PR DESCRIPTION
**Pull request by athakor**
Fixes #207

### CODE REVIEW

**Review by frankyn — APPROVED** [review]

File: google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java [hunk 1]
```diff
@@ -151,7 +151,9 @@ public StorageObject create(StorageObject object, InputStream content, Map<Optio
         continue;
       }
       so.setSize(size(so));
-      values.add(so);
+      if (so.getBucket().equals(bucket)) {
```
Comment (frankyn) [inline google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java:154]: Saw this after, but it can help to modify the first conditional, to short circuit sooner in the sequence of code.

```
if (!so.getBucket().equals(bucket) || !so.getName().startsWith(prefix)) {
        continue;
}
```

Comment (athakor) [reply google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java:154]: Ohhh i see will addressed it by creating another PR
